### ISSUE TITLE
Provide the binary with GitHubs release feature

### ISSUE THREAD

**Issue by Zilor** [TF2CutContentWiki/TF2EnhancedRockets#4]
Is easier to find the download and to get a easier overview of what has changed, imho

**Comment by TF2CutContentWiki** [comment]
> Is easier to find the download and to get a easier overview of what has changed, imho

Good suggestion! Now that I've started tinkering with this plugin and fixing things up again, I'll set up the Releases feature for this repo.

**Comment by TF2CutContentWiki** [comment]
Done!
